apiVersion: apps/v1
kind: Deployment

metadata:
  name: general-service
  

spec:
  replicas: 3

  selector:
    matchLabels:
      app: general-service

  template:
    metadata:
      labels:
        app: general-service

    spec:
      containers:
      - name: general-service
        image: general-service:v16
        imagePullPolicy: Never

        ports:
        - containerPort: 8000

        envFrom:
        - configMapRef:
            name: general-config

        - secretRef:
            name: general-secret

        livenessProbe:
          httpGet:
            path: /live
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3

        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 3
          successThreshold: 2

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"

          limits:
            cpu: "250m"
            memory: "1Gi"